### ISSUE TITLE
import django error

### ISSUE THREAD

**Issue by rotoyang** [frePPLe/frepple#678] opened 2024-11-15 01:05 UTC
Hi, I'm running frepple as VSCode dev container on Win11 - WSL2 with Docker Desktop v4.53.1 .
In the container, I'm running python 3.10.15 venv and installed lib as requirements.dev.txt(included requirements.txt).

I checked the path in the ./frepplectl.py shell, and got the result right. Import django in the shell is working good.
But it is not working correct when runplan excuting command. Here is the error msg when running ./frepplectl.py runserver started.
Is anyone seems the same issue before, please kindly advice. thx. :=)

Traceback (most recent call last):
  File "'<'string'>'", line 1, in '<'module'>'
  File "/workspaces/frepple/freppledb/common/commands.py", line 92, in <module>
    import django
ModuleNotFoundError: No module named 'django'
Error: Error executing Python command

**Comment by jdetaeye** [comment] 2024-11-16 17:14
Django is installed in a Python virtual environment in the folder "venv".  It's automatically created when you build the c++ code.
Does the folder exist?
If "./frepplectl.py shell" works, it probably does.   "./frepplectl.py runplan" also detects the venv in the same way as the shell command.

I can't reproduce in my local setup.

**Comment by jdetaeye** [comment] 2024-11-18 07:49
Closing: doesn't look like a bug or enhancement.

**Closed by jdetaeye** 2024-11-18 07:49 UTC
