### ISSUE TITLE
Model Builder / Wizard 2.0

### ISSUE THREAD

**Issue by jranita** [frePPLe/frepple#252] opened 2017-12-01 09:02 UTC
At this moment we are asking users to fill the tables to get a working model.
For Demand, Location, ... it is not a problem for most users, but resource, operation, ... have many parameters that can be a problem for a small business owner.
Also when the user looks at the amount of work he will have to fill all the tables he gets demotivated, this also happens to a planner in a bigger company who is already overwhelmed with work.

There should be an "intelligent" model builder where some questions would be made, a template for each table would be created and the user requested to input the missing data.
A step by step approach without giving the entire picture, and making the right questions so that they will not need to read the documentation.

After the model builder a second improvement would be a visual operation builder, the user would choose a "resource block", "buffer block", ..., set the properties, drag it into place and draw the lines for input/output relations with other blocks. Labview, Matlab Simulink, Emerson DeltaV... use this kind of screens.

These improvements would make frePPLe adoption much easier. The biggest pain is changing the users excel mindset. If they could start using frePPLe with almost no knowledge of PP it would be great.

**Comment by jdetaeye** [comment] 2017-12-13 09:07
Duplicate of #403

**Closed by jdetaeye** 2017-12-13 09:07 UTC
Labels: enhancement, usability
