### ISSUE TITLE
2 Demands using 1 PO

### ISSUE THREAD

**Issue by petrakozielova** [frePPLe/frepple#397] opened 2021-08-26 08:02 UTC
Hello,

we have following problem - There are two demands on same item of same quantity. We also have confirmed PO. The first demand uses this purchased items and is planned. But the second one isn't. There is also an operation which can manufacture this item. But it doesn't happen. When I change quantity of demand to different number, the manufacturing order is created and demand is planned ok. Why is it,that two demands wants to use same PO in case of same quantity?

[frepplePOproblem.xlsx](https://github.com/frePPLe/frepple/files/7052581/frepplePOproblem.xlsx)

**Comment by jdetaeye** [comment] 2021-08-31 13:18
The unplanned demand has a maxlateness of 0.   A delivery later than the due date isn't allowed.
![image](https://user-images.githubusercontent.com/5219207/131508251-7af2e842-590a-4305-9515-4bbdc73eddb2.png)

As reasons of the unplanned demand I see "awaiting supply"
![image](https://user-images.githubusercontent.com/5219207/131508473-66107998-efb4-4fac-9cac-844d73026525.png)

So, here's what happens:   When planning this demand, the solver sees there is already existing supply (within 999 days = the time horizon configured with the plan.autoFenceOperations  parameter).   Rather than triggering a new duplicate supply operation, the demand is waiting for that supply.     Since that confirmed supply is beyond the due date and a late delivery of the demand isn't allowed, the demand ends up unplanned.

All of the above is expected behavior of the solver.   Closing this ticket.

**Closed by jdetaeye** 2021-08-31 13:18 UTC
